### ISSUE TITLE
Windows 10:  loader error

### ISSUE THREAD

**Issue by Saunders1732** [brainlid/wbs_markdown#21]
When attempting to run on Windows 10 I get the following error:

internal/modules/cjs/loader.js:626 
throw err;

when running "wbsm init" the error detail is along the lines of can't fine file /index.wbsm-init.js
when running "wbsm report" the error detail is along the lines of can't fine file /index.wbsm-report.js
however I noticed that directly running
> node .../lib/wbsm-init.js works. Same for /lib/wbsm-report.js

I tried renaming "index.wbsm.js" to "wbsm.js" and now behavior matches the documentation. works rather nicely

npm version
{
  npm: '6.9.0',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  http_parser: '2.8.0',
  icu: '64.2',
  llhttp: '1.1.3',
  modules: '72',
  napi: '4',
  nghttp2: '1.38.0',
  node: '12.3.1',
  openssl: '1.1.1b',
  tz: '2019a',
  unicode: '12.1',
  uv: '1.29.1',
  v8: '7.4.288.27-node.18',
  zlib: '1.2.11'
}
hope this information is helpful I'm fairly new to node, but really interested in your tool

**Comment by brainlid** [comment]
@Saunders1732 Thank you for the report! You did a great job writing up the details. I don't have access to a Windows machine, so would you be willing to help validate a fix?

I hope to devote some time soon to testing your suggested change.

**Comment by vstiebe** [comment]
Hello! I'm using a workaround using Docker for Windows and Powershell.

- Build a container with the following Dockerfile:
~~~
FROM node:latest
WORKDIR /source
RUN npm install -g wbs-markdown
~~~
- Build command line from the folder containing the Dockerfile: `docker build -t wbsm_container .\`

After the container is built you can use the following command lines:
- Init command line: `docker run -v c:\source\wbs_test\:/source wbsm_container wbsm init`
- New command line: `docker run -v c:\source\wbs_test\:/source wbsm_container wbsm new`
- Generate command line: `docker run -v c:\source\wbs_test\:/source wbsm_container wbsm r`

You can also change the files directly from windows on `c:\source\wbs_test\` and call the generate command line.
For me it isn't a problem. But since the container is stopped after each run the _Watch for Changes and Auto-Generate Report_ will not work.

**Comment by brainlid** [comment]
If either of you (@vstiebe or @Saunders1732) can create a PR to fix this I would very much appreciate it. I don't have a good way to dev/test on Windows.

**Comment by brainlid** [comment]
I pushed a new version 1.1.4 that still works on Linux. Can you please check and verify it works on Windows?

**Comment by vstiebe** [comment]
It works.
I've tested with` wbsm init`, `wbsm new`, `wbsm r` and `wbsm w`.

**Comment by brainlid** [comment]
Awesome! Thanks! :+1:
